name: Setup pnpm
description: Setup pnpm, install dependencies and cache

runs:
  using: composite
  steps:
    - name: ⎔ Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'

    - name: 📥 Download deps
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
