name: Test Action
description: Test and lint action

runs:
  using: composite
  steps:
    - name: ⎔ Setup node
      uses: ./.github/actions/setup

    - name: ▶️ Run lint script
      shell: bash
      run: yarn lint

    - name: ▶️ Run test script
      shell: bash
      run: yarn test
