name: Codeball
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_requests.draft }}
    name: AI comment
    steps:
      - name: OpenAI Comment
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.CODEBALL_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  review:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    name: Review by Codeball
    steps:
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "true"
          failJobsWhenReviewNeeded: "false"
          codeSuggestionsFromComments: "true"
          GITHUB_TOKEN: ${{ secrets.CODEBALL_BOT_TOKEN }}
